# Generated by Django 6.0.5 on 2026-05-20 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TradingBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(default="BTC-USD", max_length=20)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=12),
                ),
                ("risk_per_trade", models.FloatField(default=0.005)),
                ("reward_ratio", models.FloatField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                (
                    "signal",
                    models.CharField(
                        choices=[("BUY", "BUY"), ("SELL", "SELL"), ("HOLD", "HOLD")],
                        max_length=10,
                    ),
                ),
                ("entry_price", models.FloatField()),
                ("stop_loss", models.FloatField()),
                ("take_profit", models.FloatField()),
                ("position_size", models.FloatField(default=0)),
                ("risk_amount", models.FloatField(default=0)),
                ("pnl", models.FloatField(default=0)),
                ("is_open", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="trading.tradingbot",
                    ),
                ),
            ],
        ),
    ]
