# Generated by Django 6.0.5 on 2026-05-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="closed_reason",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="current_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="trade",
            name="pnl_percent",
            field=models.FloatField(default=0),
        ),
    ]
