# Generated by Django 6.0.5 on 2026-05-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_trade_closed_at_trade_closed_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingbot",
            name="auto_close_profit_amount",
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name="tradingbot",
            name="profit_pot",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
