# Generated by Django 6.0.5 on 2026-05-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_tradingbot_auto_close_profit_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingbot",
            name="auto_close_loss_amount",
            field=models.FloatField(default=500),
        ),
    ]
