# Generated by Django 6.0.5 on 2026-05-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0004_tradingbot_auto_close_loss_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                ("timeframe", models.CharField(max_length=20)),
                ("total_trades", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("win_rate", models.FloatField(default=0)),
                ("total_pnl", models.FloatField(default=0)),
                ("max_drawdown", models.FloatField(default=0)),
                ("profit_factor", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
